version: 0.2
# We can listen for specific phases and execute commands per phase.
phases:

  pre_build:
    commands:
     - echo Logging in to Amazoon ECR .........
     - aws --version
     - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
     - REPOSITORY_URI=
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | CUT -C 1-7)
     - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
     

  build:
   commands:
    - echo Build started on 'date'
    - echo Building the Docker image....
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
   commands:
    - echo Build completed on 'date'
    - echo Pushing the Docker images....
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo writing image definitions file.....
    - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > techno.json
    - cat techno.json
artifacts:
  files:
    - techno.json
 
